services:
  flatnotes:
    container_name: flatnotes
    image: dullage/flatnotes:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "${FLATNOTES_PORT:-8352}:8080"
    volumes:
      - ../../local-volumes/flatnotes/data:/data
    environment:
      FLATNOTES_AUTH_TYPE: ${FLATNOTES_AUTH_TYPE:-"password"}
      FLATNOTES_USERNAME: ${FLATNOTES_USERNAME:?missing}
      FLATNOTES_PASSWORD: ${FLATNOTES_PASSWORD:?missing}
      FLATNOTES_SECRET_KEY: ${FLATNOTES_SECRET_KEY:?missing}
