services:
  open-notebook-surrealdb:
    image: surrealdb/surrealdb:v2
    container_name: open-notebook-surrealdb
    command: start --log info --user root --pass root rocksdb:/mydata/mydatabase.db
    user: root # Required for bind mounts on Linux
    ports:
      - "8000:8000"
    environment:
      SURREAL_EXPERIMENTAL_GRAPHQL: "true"
    restart: unless-stopped
    volumes:
      - ../../local-volumes/open-notebook/surrealdb/database:/mydata
      - ../../local-volumes/open-notebook/surrealdb/data:/data
      - ../../local-volumes/open-notebook/surrealdb/logs:/logs

  open-notebook:
    image: lfnovo/open_notebook:v1-latest
    ports:
      - "5055:5055" # REST API
      - "8502:8502" # Web UI
    depends_on:
      - open-notebook-surrealdb
    # required for OrbStack's local domain feature
    # comment out if not using OrbStack
    # labels:
    #   - dev.orbstack.http-port=8502
    environment:
      # allows this to work both via localhost and via OrbStack's https-enabled local domain feature
      # comment out both if not using OrbStack and/or change domain to match your project folder name
      # API_URL: http://100.117.31.1:5055
      # INTERNAL_API_URL: http://open-notebook:5055
      # REQUIRED: Change this to your own secret string
      # This encrypts your API keys in the database
      OPEN_NOTEBOOK_ENCRYPTION_KEY: "${OPEN_NOTEBOOK_ENCRYPTION_KEY}"
      # Database connection (default values - no need to change)
      SURREAL_URL: ws://open-notebook-surrealdb:8000/rpc
      SURREAL_USER: root
      SURREAL_PASSWORD: root
      SURREAL_NAMESPACE: open_notebook
      SURREAL_DATABASE: open_notebook
      # Misc Configuration
      AZURE_OPENAI_API_VERSION: "2025-04-01-preview"
      JINA_API_KEY: "${JINA_API_KEY:-}"
    restart: unless-stopped
    volumes:
      - ../../local-volumes/open-notebook/data:/app/data
