services:
  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet:latest
    ports:
      - "${SILVERBULLET_PORT:-8350}:3000"
    environment:
      SB_USER: "${SILVERBULLET_USER}:${SILVERBULLET_PASSWORD}"
    restart: unless-stopped
    volumes:
      - ../../local-volumes/silverbullet/space:/space
