services:
  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet:latest
    container_name: silverbullet
    ports:
      - "${SILVERBULLET_PORT:-8350}:3000"
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      SB_USER: "${SILVERBULLET_USER}:${SILVERBULLET_PASSWORD}"
    restart: unless-stopped
    volumes:
      - ../../local-volumes/silverbullet/space:/space
