version: 2
updates:
  - package-ecosystem: "docker-compose"
    ignore:
      - dependency-name: "unclecode/crawl4ai"
        versions:
          - "0.9.1"
    directories:
      - "/"
      - "/stack"
      - "/stack/**/*"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/New_York"
    target-branch: "main"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
