name: self-hosted-app-stack

# shared network for all applications in the stack
networks:
  default: {}

# load compose files for each application
include:
  - path:
      # Postgres
      - ./stack/postgres-shared/compose.yaml
      - ./stack/dbgate/compose.yaml
      # Personal Cloud
      - ./stack/nextcloud/compose.yaml
      # AI/LLM
      - ./stack/open-webui/compose.yaml
      - ./stack/open-notebook/compose.yaml
      - ./stack/litellm/compose.yaml
      # Search Engine
      - ./stack/degoog/compose.yaml
      - ./stack/hister/compose.yaml
      - ./stack/searxng/compose.yaml
      # Password Manager
      - ./stack/vaultwarden/compose.yaml
      # PKM Tools
      - ./stack/affine/compose.yaml
      - ./stack/blinko/compose.yaml
      - ./stack/docmost/compose.yaml
      - ./stack/flatnotes/compose.yaml
      - ./stack/karakeep/compose.yaml
      - ./stack/jotty/compose.yaml
      - ./stack/logseq/compose.yaml
      - ./stack/mealie/compose.yaml
      - ./stack/memos/compose.yaml
      - ./stack/paperless-ngx/compose.yaml
      - ./stack/silverbullet/compose.yaml
      - ./stack/siyuan/compose.yaml
      - ./stack/trilium-notes/compose.yaml
      # RSS Reader
      - ./stack/freshrss/compose.yaml
      # Task Management/Productivity
      - ./stack/super-productivity/compose.yaml
      # Automation/Workflow
      - ./stack/flowise/compose.yaml
      - ./stack/n8n/compose.yaml
      # Monitoring/Management
      - ./stack/dockpeek/compose.yaml
      - ./stack/dozzle/compose.yaml
      - ./stack/portainer/compose.yaml
      - ./stack/uptime-kuma/compose.yaml
      # SMTP Server/Mail Catcher
      - ./stack/mailpit/compose.yaml
      # API Development
      - ./stack/hoppscotch/compose.yaml
      - ./stack/restfox/compose.yaml
      - ./stack/yaade/compose.yaml
      # File Conversion
      - ./stack/vert/compose.yaml
      # Dashboard
      - ./stack/homepage/compose.yaml

    # load environment variables from .env file
    # used for interpolation in each app's compose file
    env_file:
      - .env

    extra_hosts:
      - "host.docker.internal:host-gateway"
