name: self-hosted-app-stack

# shared network for all applications in the stack
networks:
  default:
    name: self-hosted-app-stack-network

# load compose files for each application
include:
  - path:
      # AI Apps
      - ./stack/open-notebook/compose.yaml
      - ./stack/open-webui/compose.yaml
      # Search Engine
      - ./stack/searxng/compose.yaml
      # Password Manager
      - ./stack/vaultwarden/compose.yaml
      # Knowledge Management Apps
      - ./stack/affine/compose.yaml
      - ./stack/blinko/compose.yaml
      - ./stack/docmost/compose.yaml
      - ./stack/flatnotes/compose.yaml
      - ./stack/karakeep/compose.yaml
      - ./stack/jotty/compose.yaml
      - ./stack/memos/compose.yaml
      - ./stack/silverbullet/compose.yaml
      - ./stack/trilium-notes/compose.yaml
      # RSS Reader
      - ./stack/freshrss/compose.yaml
      # Productivity Apps
      - ./stack/super-productivity/compose.yaml
      # Automation/Workflow Apps
      - ./stack/flowise/compose.yaml
      - ./stack/n8n/compose.yaml
      # Monitoring/Management Apps
      - ./stack/dozzle/compose.yaml
      - ./stack/portainer/compose.yaml
      - ./stack/uptime-kuma/compose.yaml
      # Dashboard
      - ./stack/homepage/compose.yaml

    # load environment variables from .env file
    # used for interpolation in each app's compose file
    env_file:
      - .env
