name: self-hosted-ai-stack

# shared network for all applications in the stack
networks:
  default:
    name: self-hosted-ai-stack-network

# load compose files for each application
include:
  - path:
      # Core Apps
      - ./stack/searxng/docker-compose.yml
      - ./stack/open-webui/docker-compose.yml
      - ./stack/open-notebook/docker-compose.yml
      - ./stack/karakeep/docker-compose.yml
      # Notes Apps (comment out any you don't want to run)
      - ./stack/affine/docker-compose.yml
      - ./stack/blinko/docker-compose.yml
      - ./stack/docmost/docker-compose.yml
      - ./stack/flatnotes/docker-compose.yml
      - ./stack/jotty/docker-compose.yml
      - ./stack/memos/docker-compose.yml
      - ./stack/silverbullet/docker-compose.yml
      - ./stack/trilium-notes/docker-compose.yml
      # RSS App
      - ./stack/freshrss/docker-compose.yml
      # Dashboard
      - ./stack/homepage/docker-compose.yml

    # load environment variables from .env file
    # used for interpolation in each app's compose file
    env_file:
      - .env
