services:
  anythingllm:
    image: mintplexlabs/anythingllm:1.15.0
    container_name: anythingllm
    ports:
      - "${ANYTHINGLLM_PORT:-3001}:3001"
    cap_add:
      - SYS_ADMIN
    environment:
      # Adjust for your environment
      STORAGE_DIR: "/app/server/storage"
      JWT_SECRET: "8052bc60e76660a3cb1a664512dda74f9344cd3d610751ea3ffe31b8b5f34e4d"
      COMMUNITY_HUB_BUNDLE_DOWNLOADS_ENABLED: "true"
      COLLECTOR_ALLOW_ANY_IP: "true"
      PROVIDER_SUPPORTS_NATIVE_TOOL_CALLING: "generic-openai,litellm"
      # LLM_PROVIDER: "ollama"
      OLLAMA_BASE_PATH: "${OLLAMA_BASE_URL}"
      OLLAMA_MODEL_PREF: "${ANYTHINGLLM_OLLAMA_MODEL:-gemma4:12b-it-qat}"
      OLLAMA_MODEL_TOKEN_LIMIT: "${ANYTHINGLLM_OLLAMA_MODEL_TOKEN_LIMIT:-32768}"
      # EMBEDDING_ENGINE: "ollama"
      # EMBEDDING_BASE_PATH: "${OLLAMA_BASE_URL}"
      # EMBEDDING_MODEL_PREF: "${ANYTHINGLLM_OLLAMA_EMBEDDING_MODEL}"
      # EMBEDDING_MODEL_MAX_CHUNK_LENGTH: "${ANYTHINGLLM_OLLAMA_EMBED_MODEL_MAX_CHUNK_LENGTH:-8192}"
      LLM_PROVIDER: "litellm"
      LITE_LLM_MODEL_PREF: "${ANYTHINGLLM_CHAT_MODEL}"
      LITE_LLM_MODEL_TOKEN_LIMIT: "${ANYTHINGLLM_CHAT_MODEL_TOKEN_LIMIT:-128000}"
      LITE_LLM_BASE_PATH: "${BIFROST_LITELLM_API_URL}"
      LITE_LLM_API_KEY: "${BIFROST_API_KEY}"
      EMBEDDING_ENGINE: "litellm"
      EMBEDDING_MODEL_PREF: "${ANYTHINGLLM_EMBEDDING_MODEL}"
      EMBEDDING_MODEL_MAX_CHUNK_LENGTH: "${ANYTHINGLLM_EMBEDDING_MODEL_MAX_CHUNK_LENGTH:-8192}"
      TTS_PROVIDER: "native"
      # TTS_PROVIDER: "generic-openai"
      # TTS_OPEN_AI_COMPATIBLE_KEY: "${BIFROST_API_KEY}"
      # TTS_OPEN_AI_COMPATIBLE_MODEL: "${ANYTHINGLLM_AUDIO_MODEL}"
      # TTS_OPEN_AI_COMPATIBLE_VOICE_MODEL: "${ANYTHINGLLM_VOICE_MODEL}"
      # TTS_OPEN_AI_COMPATIBLE_ENDPOINT: "${BIFROST_OPENAI_SPEECH_API_URL}"
      WHISPER_PROVIDER: "local"
      # VECTOR_DB: "lancedb"
      VECTOR_DB: "pgvector"
      PGVECTOR_CONNECTION_STRING: "postgresql://${ANYTHINGLLM_POSTGRES_USER}:${ANYTHINGLLM_POSTGRES_PASSWORD}@${POSTGRES_SHARED_HOST}:${POSTGRES_SHARED_PORT}/${ANYTHINGLLM_POSTGRES_DB}"
      AGENT_SEARXNG_API_URL: "${SEARXNG_BASE_URL}"
      PASSWORDMINCHAR: "${ANYTHINGLLM_PASSWORD_MIN_CHAR:-10}"
      CONTEXT7_API_KEY: "${CONTEXT7_API_KEY}"
      ENABLED_TOOLS: "${ATLASSIAN_MCP_ENABLED_TOOLS}"
      DISABLE_TELEMETRY: "true"
      # Add any other keys here for services or settings
      # you can find in https://github.com/Mintplex-Labs/anything-llm/blob/master/docker/.env.example
    volumes:
      - ../../local-volumes/anythingllm/storage:/app/server/storage
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4096M
    depends_on:
      postgres-shared:
        condition: service_healthy
      postgres-shared-provision:
        condition: service_completed_successfully
      bifrost:
        condition: service_healthy
