services:
  jotty:
    image: ghcr.io/fccview/jotty:latest
    container_name: jotty
    ports:
      - "${JOTTY_PORT:-1122}:3000"
    deploy:
      resources:
        limits:
          memory: 256M
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ../../local-volumes/jotty/data:/app/data
      - ../../local-volumes/jotty/config:/app/config
      - ../../local-volumes/jotty/cache:/app/.next/cache
