services:
  dbx:
    image: t8y2/dbx:0.5.38
    container_name: dbx
    ports:
      - "${DBX_PORT:-4224}:4224"
    volumes:
      - ../../local-volumes/dbx/data:/app/data
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped
    environment:
      DBX_PASSWORD: "${DBX_PASSWORD}"
