services:
  nextcloud-mariadb:
    image: mariadb:11
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: "${NEXTCLOUD_MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${NEXTCLOUD_MYSQL_DATABASE}"
      MYSQL_USER: "${NEXTCLOUD_MYSQL_USER}"
      MYSQL_PASSWORD: "${NEXTCLOUD_MYSQL_PASSWORD}"
    volumes:
      - ../../local-volumes/nextcloud/db:/var/lib/mysql

  nextcloud-redis:
    image: redis:8-alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nextcloud:
    image: nextcloud:apache
    restart: unless-stopped
    depends_on:
      - nextcloud-mariadb
      - nextcloud-redis
    ports:
      - 8361:80
    environment:
      MYSQL_HOST: nextcloud-mariadb
      MYSQL_DATABASE: "${NEXTCLOUD_MYSQL_DATABASE}"
      MYSQL_USER: "${NEXTCLOUD_MYSQL_USER}"
      MYSQL_PASSWORD: "${NEXTCLOUD_MYSQL_PASSWORD}"
      REDIS_HOST: nextcloud-redis
      NEXTCLOUD_ADMIN_USER: "${NEXTCLOUD_ADMIN_USER}"
      NEXTCLOUD_ADMIN_PASSWORD: "${NEXTCLOUD_ADMIN_PASSWORD}"
      NEXTCLOUD_TRUSTED_DOMAINS: "${NEXTCLOUD_TRUSTED_DOMAINS}"
      OVERWRITEPROTOCOL: "${NEXTCLOUD_OVERWRITEPROTOCOL:-https}"
      OVERWRITEHOST: "${NEXTCLOUD_OVERWRITEHOST}"
      OVERWRITECLIURL: "${NEXTCLOUD_OVERWRITECLIURL}"
    volumes:
      - ../../local-volumes/nextcloud/app/html:/var/www/html
      - ../../local-volumes/nextcloud/app/data:/var/www/html/data
