services:
  mailcatcher:
    image: dockage/mailcatcher:latest
    container_name: mailcatcher
    restart: unless-stopped
    environment:
      MC_USER: "${MAILCATCHER_USER}"
      MC_PASS: "${MAILCATCHER_PASS}"
    ports:
      - "${MAILCATCHER_SMTP_PORT:-1025}:1025" # SMTP for other apps
      - "${MAILCATCHER_UI_PORT:-1080}:1080" # Web UI to view messages
    volumes:
      - ../../local-volumes/mailcatcher/data:/data
