services:
  trilium:
    image: triliumnext/trilium:latest
    container_name: trilium
    ports:
      - "${TRILIUM_PORT:-8351}:8080"
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      TRILIUM_DATA_DIR: /home/node/trilium-data
      TZ: ${TZ}
    restart: unless-stopped
    volumes:
      - ../../local-volumes/trilium-notes/data:/home/node/trilium-data
      - /etc/localtime:/etc/localtime:ro
