services:
  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - ../../local-volumes/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ../../local-volumes/caddy/data:/data
      - ../../local-volumes/caddy/config:/config
    restart: unless-stopped
