services:
  hoppscotch-migration:
    image: hoppscotch/hoppscotch:2026.8.0
    container_name: hoppscotch-migration-job
    command: [ "sh", "-c", "pnpm exec prisma migrate deploy" ]
    environment:
      DATABASE_URL: "postgresql://${HOPPSCOTCH_POSTGRES_USER}:${HOPPSCOTCH_POSTGRES_PASSWORD}@postgres-shared:5432/${HOPPSCOTCH_POSTGRES_DB}"
      DATA_ENCRYPTION_KEY: "${HOPPSCOTCH_DATA_ENCRYPTION_KEY}"
    volumes:
      - ../../local-volumes/hoppscotch/postgresql:/var/lib/postgresql
    depends_on:
      postgres-shared:
        condition: service_healthy
      postgres-shared-provision:
        condition: service_completed_successfully

  hoppscotch:
    image: hoppscotch/hoppscotch:2026.8.0
    container_name: hoppscotch
    environment:
      DATABASE_URL: postgresql://${HOPPSCOTCH_POSTGRES_USER}:${HOPPSCOTCH_POSTGRES_PASSWORD}@postgres-shared:5432/${HOPPSCOTCH_POSTGRES_DB}
      DATA_ENCRYPTION_KEY: "${HOPPSCOTCH_DATA_ENCRYPTION_KEY}"
      WHITELISTED_ORIGINS: http://localhost:${HOPPSCOTCH_API_PORT},http://${TAILNET_IP_ADDRESS}:${HOPPSCOTCH_API_PORT},http://localhost:${HOPPSCOTCH_PORT},http://${TAILNET_IP_ADDRESS}:${HOPPSCOTCH_PORT},http://localhost:${HOPPSCOTCH_ADMIN_PORT},http://${TAILNET_IP_ADDRESS}:${HOPPSCOTCH_ADMIN_PORT},app://localhost_3200,app://hoppscotch
      VITE_BASE_URL: http://${TAILNET_IP_ADDRESS}:${HOPPSCOTCH_PORT}
      VITE_SHORTCODE_BASE_URL: http://${TAILNET_IP_ADDRESS}:${HOPPSCOTCH_PORT}
      VITE_ADMIN_URL: http://${TAILNET_IP_ADDRESS}:${HOPPSCOTCH_ADMIN_PORT}
      VITE_BACKEND_GQL_URL: http://${TAILNET_IP_ADDRESS}:${HOPPSCOTCH_API_PORT}/graphql
      VITE_BACKEND_WS_URL: ws://${TAILNET_IP_ADDRESS}:${HOPPSCOTCH_API_PORT}/graphql
      VITE_BACKEND_API_URL: http://${TAILNET_IP_ADDRESS}:${HOPPSCOTCH_API_PORT}/v1
      ENABLE_SUBPATH_BASED_ACCESS: "false"
      MAILER_SMTP_ENABLE: "true"
      MAILER_USE_CUSTOM_CONFIGS: "true"
      MAILER_SMTP_PORT: "${MAILDEV_SMTP_PORT}"
      MAILER_SMTP_USER: "${MAILDEV_SMTP_USER}"
      MAILER_SMTP_PASSWORD: "${MAILDEV_SMTP_PASSWORD}"
      MAILER_TLS_REJECT_UNAUTHORIZED: "false"
      MAILER_SMTP_SECURE: "false"
      MAILER_ADDRESS_FROM: "${HOPPSCOTCH_MAIL_FROM}"
      MAILER_SMTP_URL: "smtp://${MAILDEV_SMTP_HOST}:${MAILDEV_SMTP_PORT}"
    ports:
      - "${HOPPSCOTCH_PORT:-8363}:3000"
      - "${HOPPSCOTCH_ADMIN_PORT:-3100}:3100"
      - "${HOPPSCOTCH_API_PORT:-3170}:3170"
    deploy:
      resources:
        limits:
          memory: 1024M
    depends_on:
      postgres-shared:
        condition: service_healthy
      postgres-shared-provision:
        condition: service_completed_successfully
      hoppscotch-migration:
        condition: service_completed_successfully
    restart: unless-stopped
