---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

background:
  image: https://images.unsplash.com/photo-1754516733606-008062751e0f
  blur: sm
  opacity: 100

color: slate

theme: dark

headerStyle: boxedWidgets

statusStyle: basic

disableIndexing: true

cardblur: md

layout:
  All Services:
    header: false
    style: row
    columns: 6
    AI/Research:
      header: true
      style: row
      columns: 1
    Automation:
      header: true
      style: row
      columns: 1
    Monitoring:
      header: true
      style: row
      columns: 1
    PKM:
      header: true
      style: row
      columns: 1
    Productivity:
      header: true
      style: row
      columns: 1
    Development:
      header: true
      style: row
      columns: 1

providers:
  finnhub: d7dvh31r01qkuebido0gd7dvh31r01qkuebido10
