---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    label: Docker
    cpu: true
    memory: true
    disk: /

- search:
    provider: custom
    target: _blank
    url: http://localhost:8348/search?q=

- openmeteo:
    label: New York, NY
    latitude: 40.730610
    longitude: -73.935242
    timezone: America/New_York
    units: imperial
    cache: 5
    format:
      maximumFractionDigits: 0
