services:
  postgres-shared:
    image: pgvector/pgvector:pg18
    container_name: postgres-shared
    restart: unless-stopped
    ports:
      - "${POSTGRES_SHARED_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_SHARED_SUPERUSER}"
      POSTGRES_PASSWORD: "${POSTGRES_SHARED_SUPERUSER_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_SHARED_DEFAULT_DB}"
      POSTGRES_INITDB_ARGS: "--data-checksums"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_SHARED_SUPERUSER}", "-d", "${POSTGRES_SHARED_DEFAULT_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ../../local-volumes/postgres-shared/postgresql:/var/lib/postgresql
