services:
  logseq:
    image: ghcr.io/logseq/logseq-webapp:latest
    container_name: logseq
    restart: unless-stopped
    ports:
      - "${LOGSEQ_PORT:-8360}:80"
    environment:
      TZ: "${TZ:-America/New_York}"
      LOGSEQ_DIRECTORY: "/Logseq"
    volumes:
      - ../../local-volumes/logseq:/Logseq
