services:
  vert:
    container_name: vert
    image: ghcr.io/vert-sh/vert:latest
    build:
      context: .
      args:
        PUB_HOSTNAME: ${VERT_PUB_HOSTNAME:-}
        PUB_PLAUSIBLE_URL: ${VERT_PUB_PLAUSIBLE_URL:-}
        PUB_ENV: ${VERT_PUB_ENV:-production}
        PUB_DISABLE_ALL_EXTERNAL_REQUESTS: ${VERT_PUB_DISABLE_ALL_EXTERNAL_REQUESTS:-false}
        PUB_VERTD_URL: ${VERT_PUB_VERTD_URL:-}
        PUB_DONATION_URL: ${VERT_PUB_DONATION_URL:-}
        PUB_STRIPE_KEY: ${VERT_PUB_STRIPE_KEY:-}
    restart: unless-stopped
    ports:
      - ${VERT_PORT:-8369}:80
  # vertd:
  #   container_name: vertd
  #   image: ghcr.io/vert-sh/vertd:latest
  #   build: .
  #   environment:
  #     - WEBHOOK_URL=${WEBHOOK_URL}
  #     - WEBHOOK_PINGS=${WEBHOOK_PINGS}
  #     - ADMIN_PASSWORD=${ADMIN_PASSWORD}
  #     - PUBLIC_URL=${PUBLIC_URL}
  #   ports:
  #     - "${PORT:-24153}:24153"

  #   # For AMD/Intel GPUs, uncomment the "devices" section - then remove
  #   # or comment out the "deploy" section and the "runtime" string used
  #   # for NVIDIA GPUs.
  #   #
  #   # devices:
  #   #   - /dev/dri
  #   #
  #   # For NVIDIA cards, keep the following section:
  #   runtime: nvidia
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [ gpu ]
