services:
  joplin-server:
    image: joplin/server:latest
    container_name: joplin-server
    restart: unless-stopped
    depends_on:
      postgres-shared:
        condition: service_healthy
    environment:
      APP_PORT: "22300"
      APP_BASE_URL: "http://${TAILNET_IP_ADDRESS}:${JOPLIN_PORT}"
      DB_CLIENT: "pg"
      POSTGRES_PASSWORD: "${JOPLIN_POSTGRES_PASSWORD}"
      POSTGRES_DATABASE: "${JOPLIN_POSTGRES_DB}"
      POSTGRES_USER: "${JOPLIN_POSTGRES_USER}"
      POSTGRES_PORT: "5432"
      POSTGRES_HOST: "postgres-shared"
      MAILER_ENABLED: 1
      MAILER_HOST: "mailpit"
      MAILER_PORT: "${MP_SMTP_PORT}"
      MAILER_SECURITY: "none"
      # MAILER_AUTH_USER: ""
      # MAILER_AUTH_PASSWORD: ""
      MAILER_NOREPLY_EMAIL: "Joplin Server <noreply@joplin-server.local>"
    ports:
      - "${JOPLIN_PORT}:22300"
    deploy:
      resources:
        limits:
          memory: 500M
