services:
  super-productivity:
    image: johannesjo/super-productivity:v18.10.0
    container_name: super-productivity
    restart: unless-stopped
    ports:
      - "${SUPER_PRODUCTIVITY_PORT:-8354}:80"
    deploy:
      resources:
        limits:
          memory: 768M
    environment:
      SP_SYNC_PROVIDER: WebDAV
      SP_WEBDAV_URL: "${NEXTCLOUD_OVERWRITECLIURL}/remote.php/dav/files/admin/nextcloud-external/SuperProductivity"
      SP_WEBDAV_USER: "${NEXTCLOUD_ADMIN_USER}"
      SP_WEBDAV_PASSWORD: "${NEXTCLOUD_ADMIN_PASSWORD}"
    depends_on:
      - nextcloud
