services:
  affine-redis:
    image: redis:8-alpine
    container_name: affine-redis
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  affine-postgres:
    image: pgvector/pgvector:pg18
    container_name: affine-postgres
    environment:
      POSTGRES_USER: "${AFFINE_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${AFFINE_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${AFFINE_POSTGRES_DB}"
      POSTGRES_INITDB_ARGS: '--data-checksums'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${AFFINE_POSTGRES_USER}", "-d", "${AFFINE_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - ../../local-volumes/affine/postgresql:/var/lib/postgresql

  affine-migration:
    image: ghcr.io/toeverything/affine:stable
    container_name: affine-migration-job
    volumes:
      - ../../local-volumes/affine/storage:/root/.affine/storage
      - ../../local-volumes/affine/config:/root/.affine/config
    command: [ "sh", "-c", "node ./scripts/self-host-predeploy.js" ]
    environment:
      REDIS_SERVER_HOST: affine-redis
      DATABASE_URL: "postgresql://${AFFINE_POSTGRES_USER}:${AFFINE_POSTGRES_PASSWORD}@affine-postgres:5432/${AFFINE_POSTGRES_DB}"
    depends_on:
      affine-postgres:
        condition: service_healthy
      affine-redis:
        condition: service_healthy

  affine:
    image: ghcr.io/toeverything/affine:stable
    container_name: affine-server
    ports:
      - '${AFFINE_PORT:-3010}:3010'
    depends_on:
      affine-redis:
        condition: service_healthy
      affine-postgres:
        condition: service_healthy
      affine-migration:
        condition: service_completed_successfully
    volumes:
      - ../../local-volumes/affine/storage:/root/.affine/storage
      - ../../local-volumes/affine/config:/root/.affine/config
    environment:
      REDIS_SERVER_HOST: affine-redis
      DATABASE_URL: "postgresql://${AFFINE_POSTGRES_USER}:${AFFINE_POSTGRES_PASSWORD}@affine-postgres:5432/${AFFINE_POSTGRES_DB}"
      CONFIG_LOCATION: ../../local-volumes/affine/config
    restart: unless-stopped
