model_list:
  - model_name: granite4.1-ollama
    model_info:
      description: Granite 4.1 (Ollama Local)
    litellm_params:
      model: ollama/granite4.1:3b
      api_base: os.environ/OLLAMA_API_BASE

  - model_name: gemma4-ollama
    model_info:
      description: Gemma 4 (Ollama Local)
    litellm_params:
      model: ollama/gemma4:latest
      api_base: os.environ/OLLAMA_API_BASE

  # - model_name: gemma4-31b-ollama-cloud
  #   model_info:
  #     description: Gemma 4 (Ollama Cloud)
  #   litellm_params:
  #     model: ollama/gemma4:31b-cloud
  #     api_base: os.environ/OLLAMA_API_BASE
  #     api_key: os.environ/OLLAMA_API_KEY

  - model_name: dolphin3-ollama
    model_info:
      description: Dolphin 3 (Ollama Local)
    litellm_params:
      model: ollama/dolphin3:latest
      api_base: os.environ/OLLAMA_API_BASE

  - model_name: qwen3.5-ollama
    model_info:
      description: Qwen 3.5 (Ollama Local)
    litellm_params:
      model: ollama/qwen3.5:latest
      api_base: os.environ/OLLAMA_API_BASE

  - model_name: deepseek-r1-ollama
    model_info:
      description: DeepSeek R1 (Ollama Local)
    litellm_params:
      model: ollama/deepseek-r1:latest
      api_base: os.environ/OLLAMA_API_BASE

  # - model_name: deepseek-v4-flash-ollama-cloud
  #   model_info:
  #     description: DeepSeek V4 Flash (Ollama Cloud)
  #   litellm_params:
  #     model: ollama/deepseek-v4-flash:cloud
  #     api_base: os.environ/OLLAMA_API_BASE
  #     api_key: os.environ/OLLAMA_API_KEY

  # - model_name: deepseek-v4-pro-ollama-cloud
  #   model_info:
  #     description: DeepSeek V4 Pro (Ollama Cloud)
  #   litellm_params:
  #     model: ollama/deepseek-v4-pro:cloud
  #     api_base: os.environ/OLLAMA_API_BASE
  #     api_key: os.environ/OLLAMA_API_KEY

  # - model_name: minimax-m2.7-ollama-cloud
  #   model_info:
  #     description: Minimax M2.7 (Ollama Cloud)
  #   litellm_params:
  #     model: ollama/minimax-m2.7:cloud
  #     api_base: os.environ/OLLAMA_API_BASE
  #     api_key: os.environ/OLLAMA_API_KEY

  # - model_name: glm-5-ollama-cloud
  #   model_info:
  #     description: GLM 5 (Ollama Cloud)
  #   litellm_params:
  #     model: ollama/glm-5:cloud
  #     api_base: os.environ/OLLAMA_API_BASE
  #     api_key: os.environ/OLLAMA_API_KEY

  - model_name: gpt-oss-ollama
    model_info:
      description: GPT OSS (Ollama Local)
    litellm_params:
      model: ollama/gpt-oss:latest
      api_base: os.environ/OLLAMA_API_BASE

  - model_name: embeddinggemma-ollama
    model_info:
      description: Embedding Gemma (Ollama Local)
      mode: embedding
    litellm_params:
      model: ollama/embeddinggemma:latest
      api_base: os.environ/OLLAMA_API_BASE

  - model_name: nomic-embed-text-v2-moe-ollama
    model_info:
      description: Nomic Embed Text v2 Moe (Ollama Local)
      mode: embedding
    litellm_params:
      model: ollama/nomic-embed-text-v2-moe:latest
      api_base: os.environ/OLLAMA_API_BASE

  - model_name: gpt-4.1-azure
    model_info:
      description: GPT 4.1 (OpenAI)
    litellm_params:
      model: azure/gpt-4.1
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: gpt-4.1-mini-azure
    model_info:
      description: GPT 4.1 Mini (OpenAI)
    litellm_params:
      model: azure/gpt-4.1-mini
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: gpt-5.3-chat-azure
    model_info:
      description: GPT 5.3 Chat (OpenAI)
    litellm_params:
      model: azure/gpt-5.3-chat
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: gpt-5.3-codex-azure
    model_info:
      description: GPT 5.3 Codex (OpenAI)
    litellm_params:
      model: azure/gpt-5.3-codex
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: gpt-5.4-azure
    model_info:
      description: GPT 5.4 (OpenAI)
    litellm_params:
      model: azure/gpt-5.4
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: gpt-5.4-mini-azure
    model_info:
      description: GPT 5.4 Mini (OpenAI)
    litellm_params:
      model: azure/gpt-5.4-mini
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: gpt-5.4-nano-azure
    model_info:
      description: GPT 5.4 Nano (OpenAI)
    litellm_params:
      model: azure/gpt-5.4-nano
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: gpt-5.4-pro-azure
    model_info:
      description: GPT 5.4 Pro (OpenAI)
    litellm_params:
      model: azure/gpt-5.4-pro
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: gpt-5.5-azure
    model_info:
      description: GPT 5.5 (OpenAI)
    litellm_params:
      model: azure/gpt-5.5-1
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: gpt-4o-mini-transcribe-azure
    model_info:
      description: GPT 4o Mini Transcribe (OpenAI)
      mode: audio_transcription
    litellm_params:
      model: azure/gpt-4o-mini-transcribe
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: gpt-4o-mini-tts-azure
    model_info:
      description: GPT 4o Mini TTS (OpenAI)
      mode: audio_speech
    litellm_params:
      model: azure/gpt-4o-mini-tts
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: gpt-audio-1.5-azure
    model_info:
      description: GPT Audio 1.5 (OpenAI)
      mode: audio_speech
    litellm_params:
      model: azure/gpt-audio-1.5-1
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: gpt-oss-120b-azure
    model_info:
      description: GPT OSS 120B (OpenAI)
    litellm_params:
      model: azure/gpt-oss-120b
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: gpt-image-1-mini-azure
    model_info:
      description: GPT Image 1 Mini (OpenAI)
      mode: image_generation
    litellm_params:
      model: azure/gpt-image-1-mini
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: gpt-image-1.5-azure
    model_info:
      description: GPT Image 1.5 (OpenAI)
      mode: image_generation
    litellm_params:
      model: azure/gpt-image-1.5
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: gpt-image-2-azure
    model_info:
      description: GPT Image 2 (OpenAI)
      mode: image_generation
    litellm_params:
      model: azure/gpt-image-2-1
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: sora-2-azure
    model_info:
      description: Sora 2 (OpenAI)
      mode: video_generation
    litellm_params:
      model: azure/sora2
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: text-embedding-3-small-azure
    model_info:
      description: Text Embedding 3 Small (OpenAI)
      mode: embedding
    litellm_params:
      model: azure/text-embedding-3-small
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: text-embedding-3-large-azure
    model_info:
      description: Text Embedding 3 Large (OpenAI)
      mode: embedding
    litellm_params:
      model: azure/text-embedding-3-large
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: embed-v4.0-azure
    model_info:
      description: Embed v4.0 (Cohere)
      mode: embedding
    litellm_params:
      model: azure_ai/embed-v-4-0
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: cohere-rerank-v4.0-fast-azure
    model_info:
      description: Rerank v4.0 Fast (Cohere)
      mode: rerank
    litellm_params:
      model: azure_ai/Cohere-rerank-v4.0-fast
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: cohere-rerank-v4.0-pro-azure
    model_info:
      description: Rerank v4.0 Pro (Cohere)
      mode: rerank
    litellm_params:
      model: azure_ai/Cohere-rerank-v4.0-pro
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: claude-opus-4.7-azure
    model_info:
      description: Claude Opus 4.7 (Anthropic)
    litellm_params:
      model: azure_ai/claude-opus-4-7
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: claude-opus-4.6-azure
    model_info:
      description: Claude Opus 4.6 (Anthropic)
    litellm_params:
      model: azure_ai/claude-opus-4-6
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: claude-sonnet-4.6-azure
    model_info:
      description: Claude Sonnet 4.6 (Anthropic)
    litellm_params:
      model: azure_ai/claude-sonnet-4-6
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: claude-opus-4.5-azure
    model_info:
      description: Claude Opus 4.5 (Anthropic)
    litellm_params:
      model: azure_ai/claude-opus-4-5
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: claude-sonnet-4.5-azure
    model_info:
      description: Claude Sonnet 4.5 (Anthropic)
    litellm_params:
      model: azure_ai/claude-sonnet-4-5
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: claude-haiku-4.5-azure
    model_info:
      description: Claude Haiku 4.5 (Anthropic)
    litellm_params:
      model: azure_ai/claude-haiku-4-5
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: grok-code-fast-1-azure
    model_info:
      description: Grok Code Fast 1 (xAI)
    litellm_params:
      model: azure_ai/grok-code-fast-1
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: grok-4-1-fast-non-reasoning-azure
    model_info:
      description: Grok 4.1 Fast Non-Reasoning (xAI)
    litellm_params:
      model: azure_ai/grok-4-1-fast-non-reasoning
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: grok-4-1-fast-reasoning-azure
    model_info:
      description: Grok 4.1 Fast Reasoning (xAI)
    litellm_params:
      model: azure_ai/grok-4-1-fast-reasoning
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: grok-4-2-non-reasoning-azure
    model_info:
      description: Grok 4.2 Non-Reasoning (xAI)
    litellm_params:
      model: azure_ai/grok-4-20-non-reasoning-1
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: grok-4-2-reasoning-azure
    model_info:
      description: Grok 4.2 Reasoning (xAI)
    litellm_params:
      model: azure_ai/grok-4-20-reasoning-1
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: deepseek-v4-flash-azure
    model_info:
      description: DeepSeek v4 Flash (DeepSeek AI)
    litellm_params:
      model: azure_ai/DeepSeek-V4-Flash
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: deepseek-v3.2-azure
    model_info:
      description: DeepSeek v3.2 (DeepSeek AI)
    litellm_params:
      model: azure_ai/DeepSeek-V3.2
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: deepseek-v3.1-azure
    model_info:
      description: DeepSeek v3.1 (DeepSeek AI)
    litellm_params:
      model: azure_ai/DeepSeek-V3.1
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: deepseek-r1-azure
    model_info:
      description: DeepSeek R1 (DeepSeek AI)
    litellm_params:
      model: azure_ai/DeepSeek-R1-0528
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: flux-2-pro-azure
    model_info:
      description: FLUX 2 Pro (Black Forest Labs)
      mode: image_generation
    litellm_params:
      model: azure_ai/FLUX.2-pro-1
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  # - model_name: flux-2-flex-azure
  #   model_info:
  #     description: FLUX 2 Flex (Black Forest Labs)
  #     mode: image_generation
  #   litellm_params:
  #     model: azure_ai/FLUX.2-flex-1
  #     api_base: os.environ/AZURE_API_BASE
  #     api_key: os.environ/AZURE_API_KEY

  - model_name: kimi-k2.6-azure
    model_info:
      description: Kimi K2.6 (Moonshot AI)
    litellm_params:
      model: azure_ai/Kimi-K2.6-1
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: kimi-k2.5-azure
    model_info:
      description: Kimi K2.5 (Moonshot AI)
    litellm_params:
      model: azure_ai/Kimi-K2.5-1
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

litellm_settings:
  drop_params: true
  telemetry: false
  set_verbose: true
  cache: true
  # cache_params:
  #   type: qdrant-semantic
  #   qdrant_semantic_cache_embedding_model: text-embedding-3-small-azure # the model should be defined on the model_list
  #   qdrant_collection_name: litellm_cache
  #   qdrant_quantization_config: binary
  #   qdrant_semantic_cache_vector_size: 1536 # vector size must match embedding model dimensionality
  #   similarity_threshold: 0.8 # similarity threshold for semantic cache

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  detailed_debug: true
  store_prompts_in_spend_logs: true
  database_url: os.environ/DATABASE_URL

logging:
  level: "DEBUG"
  log_requests: true
  log_responses: true

search_tools:
  - search_tool_name: searxng-search
    litellm_params:
      search_provider: searxng
      api_base: os.environ/SEARXNG_API_BASE

mcp_servers:
  atlassian:
    url: "http://atlassian-mcp:9000/mcp"
    description: "Readonly Jira and Confluence tools for accessing data in our instances"
    spec_path: ""
    auth_type: none

  mermaid:
    url: "https://mcp.mermaid.ai/mcp"
    description: "Enables AI assistants to create, validate, and render Mermaid diagrams"
    spec_path: ""
    auth_type: none

  context7:
    url: "https://mcp.context7.com/mcp"
    description: "Pull up-to-date version-specific llm-friendly documentation and
      code examples for any library"
    spec_path: ""
    auth_type: bearer_token
    auth_value: os.environ/CONTEXT7_API_KEY

  tdx:
    url: os.environ/TDX_MCP_SERVER_URL
    description: "Full-text search tools with access to TDX tickets and KB articles"
    spec_path: ""
    auth_type: none
  # model_info -> mode - one of:
  # chat,
  # embedding,
  # completion,
  # image_generation,
  # audio_transcription,
  # audio_speech,
  # image_generation,
  # moderation,
  # rerank,
  # realtime
  # batch
  # ocr
