services:
  omni-tools:
    image: iib0011/omni-tools:latest
    container_name: omni-tools
    ports:
      - "${OMNI_TOOLS_PORT:-8080}:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1024M
