services:
  agenticseek-redis:
    image: redis:8-alpine
    container_name: agenticseek-redis
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]
    restart: unless-stopped
    volumes:
      - ../../local-volumes/agenticseek/redis/data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  agenticseek-backend:
    image: agenticseek/backend:latest
    container_name: agenticseek-backend
    restart: unless-stopped
    depends_on:
      agenticseek-redis:
        condition: service_healthy
    ports:
      - "7777:7777"
    environment:
      SEARXNG_BASE_URL: "http://searxng:8348"
      REDIS_BASE_URL: "redis://agenticseek-redis:6379/0"
      WORK_DIR: "/app/work_dir"
      OLLAMA_PORT: "11434"
      LM_STUDIO_PORT: "1234"

  agenticseek:
    image: agenticseek/frontend:latest
    container_name: agenticseek-frontend
    restart: unless-stopped
    depends_on:
      agenticseek-backend:
        condition: service_started
      agenticseek-redis:
        condition: service_healthy
    ports:
      - "${AGENTICSEEK_PORT:-8367}:3000"
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:7777"
      NEXT_PUBLIC_SEARXNG_URL: "http://localhost:8348"
    volumes:
      - ../../local-volumes/agenticseek/frontend:/app/.next/cache
