services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    ports:
      - "5230:5230"
    environment:
      MEMOS_PORT: 5230
      MEMOS_DRIVER: postgres
      MEMOS_DSN: "postgres://${MEMOS_POSTGRES_USER}:${MEMOS_POSTGRES_PASSWORD}@memos-postgres:5432/${MEMOS_POSTGRES_DB}?sslmode=disable"
      # MEMOS_INSTANCE_URL: http://memos.example.com
    restart: unless-stopped
    volumes:
      - ../../local-volumes/memos/data:/var/opt/memos

  memos-postgres:
    image: pgvector/pgvector:pg17
    container_name: memos-postgres
    environment:
      POSTGRES_USER: "${MEMOS_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${MEMOS_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${MEMOS_POSTGRES_DB}"
      POSTGRES_INITDB_ARGS: '--data-checksums'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${MEMOS_POSTGRES_USER}", "-d", "${MEMOS_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - ../../local-volumes/memos/postgresql/data:/var/lib/postgresql/data
