services:
  open-webui-postgres:
    image: pgvector/pgvector:pg18
    container_name: open-webui-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${OPEN_WEBUI_POSTGRES_DB}"
      POSTGRES_USER: "${OPEN_WEBUI_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${OPEN_WEBUI_POSTGRES_PASSWORD}"
    volumes:
      - ../../local-volumes/open-webui/postgresql:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $OPEN_WEBUI_POSTGRES_USER -d $OPEN_WEBUI_POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 10

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    depends_on:
      open-webui-postgres:
        condition: service_healthy
    ports:
      - "${OPEN_WEBUI_PORT:-3000}:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DOCKER: "true"

      WEBUI_SECRET_KEY: "${OPEN_WEBUI_SECRET_KEY}"
      WEBUI_AUTH: "${OPEN_WEBUI_AUTH:-true}"
      WEBUI_ADMIN_EMAIL: "${OPEN_WEBUI_ADMIN_EMAIL:-}"
      WEBUI_ADMIN_PASSWORD: "${OPEN_WEBUI_ADMIN_PASSWORD:-}"
      WEBUI_ADMIN_NAME: "${OPEN_WEBUI_ADMIN_NAME:-}"

      ENABLE_SIGNUP: false
      ENABLE_DIRECT_CONNECTIONS: "true"
      ENABLE_CHANNELS: "true"
      ENABLE_EASTER_EGGS: "true"
      ENABLE_USER_STATUS: "false"
      ENABLE_PUBLIC_ACTIVE_USERS_COUNT: "false"
      ENABLE_BASE_MODELS_CACHE: "true"
      MODELS_CACHE_TTL: 300

      DATABASE_URL: "postgresql://${OPEN_WEBUI_POSTGRES_USER}:${OPEN_WEBUI_POSTGRES_PASSWORD}@open-webui-postgres:5432/${OPEN_WEBUI_POSTGRES_DB}"
      VECTOR_DB: "pgvector"
      PGVECTOR_DB_URL: "postgresql://${OPEN_WEBUI_POSTGRES_USER}:${OPEN_WEBUI_POSTGRES_PASSWORD}@open-webui-postgres:5432/${OPEN_WEBUI_POSTGRES_DB}"
      PGVECTOR_CREATE_EXTENSION: "true"
      UVICORN_WORKERS: 1

      ENABLE_OLLAMA_API: "true"
      OLLAMA_BASE_URL: "${OLLAMA_API_URL:-}"
      OLLAMA_API_KEY: "${OLLAMA_API_KEY:-}"

      ENABLE_OPENAI_API: "true"

      ENABLE_WEB_SEARCH: "true"
      ENABLE_SEARCH_QUERY_GENERATION: "true"
      WEB_SEARCH_RESULT_COUNT: 12
      WEB_SEARCH_CONCURRENT_REQUESTS: 3
      WEB_SEARCH_ENGINE: "searxng"
      SEARXNG_QUERY_URL: "http://searxng:8080/search?q=<query>"

      CONTEXT7_API_KEY: "${CONTEXT7_API_KEY:-}"

      TOOL_SERVER_CONNECTIONS: >-
        [
          {
            "type": "mcp",
            "url": "https://mcp.context7.com/mcp",
            "spec_type": "url",
            "spec": "",
            "path": "",
            "auth_type": "none",
            "headers": {
              "CONTEXT7_API_KEY": "${CONTEXT7_API_KEY}"
            },
            "key": "",
            "config": { "enable": true },
            "info": {
              "id": "context7",
              "name": "Context7",
              "description": "Pull up-to-date version-specific llm-friendly documentation and code examples for any library"
            }
          },
          {
            "type": "mcp"
            "url": "https://mcp.mermaid.ai/mcp",
            "spec_type": "url",
            "spec": "",
            "path": "",
            "auth_type": "none",
            "headers": {},
            "key": "",
            "config": { "enable": true },
            "info": {
              "id": "mermaid",
              "name": "Mermaid",
              "description": "The Mermaid MCP Server enables AI assistants to create, validate, and render Mermaid diagrams"
            }
          }
        ]

      # default suggestions shown in chat UI, modify or remove as you see fit
      DEFAULT_PROMPT_SUGGESTIONS: >-
        [
          {
            "title": [ "Help me study", "vocabulary for a college entrance exam" ],
            "content": "Help me study vocabulary: write a sentence for me to fill in the blank, and I'll try to pick the correct option."
          },
          {
            "title": [ "Give me ideas", "for what to do with my kids' art" ],
            "content": "What are 5 creative things I could do with my kids' art? I don't want to throw them away, but it's also so much clutter."
          },
          {
            "title": [ "Tell me a fun fact", "about the Roman Empire" ],
            "content": "Tell me a random fun fact about the Roman Empire"
          },
          {
            "title": [ "Show me a code snippet", "of a website's sticky header" ],
            "content": "Show me a code snippet of a website's sticky header in CSS and JavaScript."
          },
          {
            "title": [ "Explain options trading", "if I'm familiar with buying and selling stocks" ],
            "content": "Explain options trading in simple terms if I'm familiar with buying and selling stocks."
          },
          {
            "title": [ "Overcome procrastination", "give me tips" ],
            "content": "Could you start by asking me about instances when I procrastinate the most and then give me some suggestions to overcome it?"
          }
        ]

    volumes:
      - ../../local-volumes/open-webui/data:/app/backend/data:Z
