services:
  hindsight:
    image: ghcr.io/vectorize-io/hindsight:0.8.6
    container_name: hindsight
    restart: unless-stopped
    ports:
      - "${HINDSIGHT_API_PORT:-8888}:8888"
      - "${HINDSIGHT_UI_PORT:-9999}:9999"
    deploy:
      resources:
        limits:
          memory: 8192M
    environment:
      HINDSIGHT_API_AUDIT_LOG_ENABLED: "true"
      HINDSIGHT_API_LLM_PROVIDER: "openai"
      HINDSIGHT_API_LLM_BASE_URL: "${HEADROOM_OPENAI_API_URL_INTERNAL}"
      HINDSIGHT_API_LLM_API_KEY: "${BIFROST_API_KEY}"
      HINDSIGHT_API_LLM_MODEL: "fireworks/gpt-oss-20b"
      HINDSIGHT_API_RETAIN_LLM_MODEL: "fireworks/gpt-oss-20b"
      HINDSIGHT_API_REFLECT_LLM_MODEL: "fireworks/gpt-oss-120b"
      HINDSIGHT_API_CONSOLIDATION_LLM_MODEL: "fireworks/gpt-oss-120b"
      # HINDSIGHT_API_LLM_REASONING_EFFORT: "none"
      HINDSIGHT_API_DATABASE_SCHEMA: "${HINDSIGHT_API_DATABASE_SCHEMA:-public}"
      HINDSIGHT_API_DATABASE_URL: "${HINDSIGHT_API_DATABASE_URL:-pg0}"
      HINDSIGHT_API_DATABASE_BACKEND: "${HINDSIGHT_API_DATABASE_BACKEND:-postgresql}"
      HINDSIGHT_API_MENTAL_MODELS_CRON: "0 */6 * * *" # every 6 hours
      # HINDSIGHT_API_DISABLE_DB_MAINTENANCE_DISCOVERY: "1"
      HINDSIGHT_API_WORKER_ID: "hindsight-worker-1"
      HINDSIGHT_API_EMBEDDINGS_PROVIDER: "local"
      HINDSIGHT_API_EMBEDDINGS_LOCAL_MODEL: "BAAI/bge-small-en-v1.5"
      HINDSIGHT_API_RERANKER_PROVIDER: "local"
      HINDSIGHT_API_RERANKER_LOCAL_MODEL: "cross-encoder/ms-marco-MiniLM-L-6-v2"
      # HINDSIGHT_API_EMBEDDINGS_PROVIDER: "openai"
      # HINDSIGHT_API_EMBEDDINGS_OPENAI_BASE_URL: "${HEADROOM_OPENAI_API_URL_INTERNAL}"
      # HINDSIGHT_API_EMBEDDINGS_OPENAI_API_KEY: "${BIFROST_API_KEY}"
      # HINDSIGHT_API_EMBEDDINGS_OPENAI_MODEL: "openai/text-embedding-3-small"
      # HINDSIGHT_API_EMBEDDINGS_OPENAI_DIMENSIONS: "1536"
    depends_on:
      bifrost:
        condition: service_healthy
      headroom:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

    volumes:
      - ../../local-volumes/hindsight/data/.pg0:/home/hindsight/.pg0
      - ../../local-volumes/hindsight/data:/home/hindsight
