services:
  restfox:
    image: flawiddsouza/restfox:0.40.0
    container_name: restfox
    restart: unless-stopped
    ports:
      - "${RESTFOX_PORT:-8365}:4004"
    deploy:
      resources:
        limits:
          memory: 512M
