services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "${MAILPIT_PORT:-8371}:8025"
      - "${MAILPIT_SMTP_PORT:-1025}:1025"
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      TZ: "${TZ}"
      MP_MAX_MESSAGES: "${MAILPIT_MAX_MESSAGES:-5000}"
      MP_DATABASE: "${MAILPIT_DATABASE:-/data/mailpit.db}"
      MP_SMTP_AUTH_ACCEPT_ANY: "${MAILPIT_SMTP_AUTH_ACCEPT_ANY:-1}"
      MP_SMTP_AUTH_ALLOW_INSECURE: "${MAILPIT_SMTP_AUTH_ALLOW_INSECURE:-1}"
    volumes:
      - ../../local-volumes/mailpit/data:/data
