services:
  n8n:
    image: n8nio/n8n:2.31.3
    container_name: n8n
    restart: unless-stopped
    ports:
      - "${N8N_PORT:-5678}:5678"
    deploy:
      resources:
        limits:
          memory: 4096M
    environment:
      N8N_HOST: "${TAILNET_DOMAIN}" # Set to your domain
      N8N_PORT: "${N8N_PORT:-5678}"
      N8N_PROTOCOL: "http" # Use "http" for local access
      N8N_WEBHOOK_URL: "http://${TAILNET_DOMAIN}:${N8N_PORT:-5678}/" # Your public URL for webhooks
      N8N_ENCRYPTION_KEY: "${N8N_ENCRYPTION_KEY}"
      N8N_UNVERIFIED_PACKAGES_ENABLED: "false"
      N8N_RUNNERS_TASK_TIMEOUT: "300"
      N8N_COMPRESSION_NODE_MAX_DECOMPRESSED_SIZE_BYTES: "1073741824" # 1024 MB
      N8N_COMPRESSION_NODE_MAX_ZIP_ENTRIES: "1000"
      NODES_EXCLUDE: "[]"
      DB_TYPE: "postgresdb"
      DB_POSTGRESDB_HOST: "postgres-shared"
      DB_POSTGRESDB_PORT: "5432"
      DB_POSTGRESDB_DATABASE: "${N8N_POSTGRES_DB}"
      DB_POSTGRESDB_USER: "${N8N_POSTGRES_USER}"
      DB_POSTGRESDB_PASSWORD: "${N8N_POSTGRES_PASSWORD}"
      N8N_SECURE_COOKIE: "${N8N_SECURE_COOKIE}"
      GENERIC_TIMEZONE: "${TZ}"
    volumes:
      - ../../local-volumes/n8n/data:/home/node/.n8n
      - /Volumes/Seagate/n8n:/data/external:rw
    depends_on:
      n8n-qdrant:
        condition: service_started
      postgres-shared:
        condition: service_healthy
      bifrost:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:5678/healthz || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  n8n-qdrant:
    image: qdrant/qdrant:v1.18.2
    container_name: n8n-qdrant
    restart: unless-stopped
    ports:
      - 6333:6333
    environment:
      QDRANT__TELEMETRY_DISABLED: "true"
    volumes:
      - ../../local-volumes/n8n/qdrant/storage:/qdrant/storage
