services:
  docmost-postgres:
    image: pgvector/pgvector:pg18
    container_name: docmost-postgres
    environment:
      POSTGRES_DB: ${DOCMOST_POSTGRES_DB:-docmost}
      POSTGRES_USER: ${DOCMOST_POSTGRES_USER:-docmost}
      POSTGRES_PASSWORD: ${DOCMOST_POSTGRES_PASSWORD:?missing}
    restart: unless-stopped
    volumes:
      - ../../local-volumes/docmost/postgresql:/var/lib/postgresql

  docmost-redis:
    image: redis:8-alpine
    container_name: docmost-redis
    command: [ "redis-server", "--appendonly", "yes", "--maxmemory-policy", "noeviction" ]
    restart: unless-stopped
    volumes:
      - ../../local-volumes/docmost/redis/data:/data

  docmost:
    image: docmost/docmost:latest
    container_name: docmost
    depends_on:
      docmost-postgres:
        condition: service_started
      docmost-redis:
        condition: service_started
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    environment:
      APP_URL: "http://localhost:7889"
      APP_SECRET: ${DOCMOST_APP_SECRET:?missing}
      DATABASE_URL: "postgresql://${DOCMOST_POSTGRES_USER}:${DOCMOST_POSTGRES_PASSWORD}@docmost-postgres:5432/${DOCMOST_POSTGRES_DB}"
      REDIS_URL: 'redis://docmost-redis:6379'
      AI_DRIVER: openai
      OPENAI_API_KEY: ${AZURE_FOUNDRY_API_KEY:?missing}
      AI_EMBEDDING_MODEL: text-embedding-3-small
      AI_COMPLETION_MODEL: gpt-5.4-mini
      OPENAI_API_URL: ${AZURE_FOUNDRY_OPENAI_BASE_URL:?missing}
      # AI_DRIVER: ollama
      # OLLAMA_API_URL: ${OLLAMA_BASE_URL:?missing}
      # OLLAMA_API_KEY: ${OLLAMA_API_KEY:-}
      # AI_EMBEDDING_MODEL: mxbai-embed-large
      # AI_COMPLETION_MODEL: gemma4
    ports:
      - "${DOCMOST_PORT:-7889}:3000"
    restart: unless-stopped
    volumes:
      - ../../local-volumes/docmost/storage:/app/data/storage
