services:
  docmost-redis:
    image: redis:8-alpine
    container_name: docmost-redis
    command:
      - redis-server
      - --appendonly yes
      - --maxmemory 256mb # a bit under container limit so you leave room for Redis overhead
      - --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 320M
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - ../../local-volumes/docmost/redis/data:/data

  docmost:
    image: docmost/docmost:latest
    container_name: docmost
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      postgres-shared:
        condition: service_healthy
      docmost-redis:
        condition: service_healthy
    environment:
      APP_URL: "http://localhost:7889"
      APP_SECRET: ${DOCMOST_APP_SECRET:?missing}
      DATABASE_URL: "postgresql://${DOCMOST_POSTGRES_USER}:${DOCMOST_POSTGRES_PASSWORD}@postgres-shared:5432/${DOCMOST_POSTGRES_DB}"
      REDIS_URL: 'redis://docmost-redis:6379'
      AI_DRIVER: openai
      OPENAI_API_KEY: ${AZURE_FOUNDRY_API_KEY:?missing}
      AI_EMBEDDING_MODEL: text-embedding-3-small
      AI_COMPLETION_MODEL: gpt-5.4-mini
      OPENAI_API_URL: ${AZURE_FOUNDRY_OPENAI_BASE_URL:?missing}
      # AI_DRIVER: ollama
      # OLLAMA_API_URL: ${OLLAMA_BASE_URL:?missing}
      # OLLAMA_API_KEY: ${OLLAMA_API_KEY:-}
      # AI_EMBEDDING_MODEL: mxbai-embed-large
      # AI_COMPLETION_MODEL: gemma4
    ports:
      - "${DOCMOST_PORT:-7889}:3000"
    restart: unless-stopped
    volumes:
      - ../../local-volumes/docmost/storage:/app/data/storage
